variavel = input("Digite algo: ")
print('O tipo primitivo desse valor é', type(variavel))
print('Só tem espacos?', variavel.isspace())
print('É um número?', variavel.isnumeric())
print('É alfabético?', variavel.isalpha())
print('É alfanúmerico?', variavel.isalnum())
print('Está em maiúsculas?', variavel.isupper())
print('Está em minúsculas?', variavel.islower())
print('Está capitalizada?', variavel.istitle())
